export const CHATS = [
  {
    title:'Андрей',
    desc:'Изображение',
    avatarColor:'#FFFFFF',
    time: '10:49',
    messagesCount: '1',
  },
  {
    title:'Киноклуб',
    desc:'стикер',
    avatarColor:'#AB3245',
    time: '12:00',
  },
  {
    title:'Илья',
    desc:'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
    avatarColor:'#7E6C63',
    time: '13:66',
    messagesCount: '10',
  },
  {
    title:'Такого времени не бывает',
    desc:'совсем забыл',
    avatarColor:'#',
    time: '13:77',
  },
  {
    title:'Вадим',
    desc:'круто!',
    avatarColor:'#2917F4',
    time: '14.00',
  },
  {
    title:'1, 2, 3',
    desc:'Миллионы россиян ежедневн...',
    avatarColor:'#3F4489',
    time: '15:12',
    messagesCount: '45',
  },
  {
    title:'Design Destroyer',
    desc:'В 2008 году художник Jon Rafman  начал собирать...',
    avatarColor:'#DB678A',
    time: 'Пт',
    messagesCount: '99+',
  },
  {
    title:'Day.',
    desc:'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
    avatarColor:'#74C3BF',
    time: 'Ср',
  },
  {
    title:'Стас Рогозин',
    desc:'Можно или сегодня или завтра вечером.',
    avatarColor:'#FFFFFF',
    time: 'Пн',
  },
  {
    title:'тет-а-теты',
    desc:'И Human Interface Guidelines...',
    avatarColor:'#43F417',
    time: 'Пн',
  },
  {
    title:'Группа № 13',
    desc:'стикер',
    avatarColor:'#17F4BF',
    time: '1 Мая 2022',
  },
  {
    title:'Как заработать много...',
    desc:'Учимся на Я.Практикум!',
    avatarColor:'#BE9D26',
    time: '20 Апр 2021',
  },
  {
    title:'###',
    desc:'За что мне это всё?',
    avatarColor:'#FF0000',
    time: '14 Мая 2020',
  },
  {
    title:'Андрей',
    desc:'Изображение',
    avatarColor:'#FFFFFF',
    time: '10:49',
  },
  {
    title:'Киноклуб',
    desc:'стикер',
    avatarColor:'#AB3245',
    time: '12:00',
  },
  {
    title:'Илья',
    desc:'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
    avatarColor:'#7E6C63',
    time: '13:66',
  },
]
