const TEXT_LIMIT = 50;

const CHATS = [
  {
    id: '123',
    title: 'Андрей',
    avatar: null,
    avatarColor: '#FFFFFF',
    unread_count: 1,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '10:49',
      content: 'Изображение',
    },
  },
  {
    id: '1234',
    title: 'Киноклуб',
    avatar: null,
    avatarColor: '#AB3245',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12:00',
      content: 'стикер',
    },
  },
  {
    id: 'id',
    title: 'Илья',
    avatar: null,
    avatarColor: '#7E6C63',
    unread_count: 10,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '13:66',
      content: `${'Так увлёкся работой по курсу, что совсем забыл его анонсировать на следующий год. Вот блин, как всегда всё не так, как я планировал изначально. Простите меня охохох как страшно жить и писать эти строки пойду утоплюсь хахахохо'.substring(0, TEXT_LIMIT)}...`,
    },
  },
  {
    id: '1236',
    title: 'Такого времени не бывает',
    avatar: null,
    avatarColor: '#',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '14.00',
      content: 'совсем забыл',
    },
  },
  {
    id: '1237',
    title: 'Вадим',
    avatar: null,
    avatarColor: '#2917F4',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '15:12',
      content: 'круто!',
    },
  },
  {
    id: '1238',
    title: '1, 2, 3',
    avatar: null,
    avatarColor: '#3F4489',
    unread_count: 45,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Пт',
      content: `${'Миллионы россиян ежедневно выпивают по три стакана воды с примесью трёх чайных ложек самого обычного раствора из топора. Мы делаем самый насыщенный раствор из топора. Если вы купите наш раствор сейчас, то получите в подарок обыкновенную вилку.'.substring(0, TEXT_LIMIT)}...`,
    },
  },
  {
    id: '1239',
    title: 'Design Destroyer',
    avatar: null,
    avatarColor: '#DB678A',
    unread_count: '99+',
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Ср',
      content: `${'В 2008 году художник Jon Rafman начал собирать своё портфолио. Это портфолио настолько профессионально собрано, что все его знакомые были в восторге. Люди стояли в очереди, чтобы посмотреть на это портфолио.'.substring(0, TEXT_LIMIT)}...`,
    },
  },
  {
    id: '12310',
    title: 'Day.',
    avatar: null,
    avatarColor: '#74C3BF',
    unread_count: 99,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Пн',
      content: `${'Так увлёкся работой по курсу, что совсем забыл его анонсировать. Так что анонсирую сейчас. Курс очень крутой и раскрывает не только основные темы, но и множество нюансов, которые можно обнаружить только на практике.'.substring(0, TEXT_LIMIT)}...`,
    },
  },
  {
    id: '12311',
    title: 'Стас Рогозин',
    avatar: null,
    avatarColor: '#FFFFFF',
    unread_count: '99+',
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Пн',
      content: 'Можно или сегодня или завтра вечером.',
    },
  },
  {
    id: '12312',
    title: 'тет-а-теты',
    avatar: null,
    avatarColor: '#43F417',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '1 Мая 2022',
      content: `${'И Human Interface Guidelines лучше изучить уже сегодня, иначе вы отстанете по программе.'.substring(0, TEXT_LIMIT)}...`,
    },
  },
  {
    id: '12313',
    title: 'Группа № 13',
    avatar: null,
    avatarColor: '#17F4BF',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '20 Апр 2021',
      content: 'стикер',
    },
  },
  {
    id: '12314',
    title: 'Учимся на Я.Практикум!',
    avatar: null,
    avatarColor: '#BE9D26',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '15 Апр 2020',
      content: `${'Как заработать много новых впечатлений от поездок в простые места? Обращайтесь в нашу экскурсионную организацию и мы покажем, как :-)'.substring(0, TEXT_LIMIT)}...`,
    },
  },
  {
    id: '12315',
    title: '###',
    avatar: null,
    avatarColor: '#FF0000',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '14 Мая 2019',
      content: 'За что мне это всё?',
    },
  },
  {
    id: '12316',
    title: 'Андрей',
    avatar: null,
    avatarColor: '#FFFFFF',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '25 Апр 2018',
      content: 'Изображение',
    },
  },
  {
    id: '12317',
    title: 'Киноклуб',
    avatar: null,
    avatarColor: '#AB3245',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '2010',
      content: 'стикер',
    },
  },
  {
    id: '12318',
    title: 'Илья32',
    avatar: null,
    avatarColor: '#7E6C63',
    unread_count: 0,
    last_message: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '1993',
      content: 'Ребят, дайте ссылочку на материалы пожалуйста',
    },
  },
];

export default CHATS;
