export const CHATS = [
  {
    id: '123',
    title: 'Андрей',
    avatar: null,
    avatarColor: '#FFFFFF',
    unreadCount: 1,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '10:49',
      content: 'Изображение',
    },
  },
  {
    id: '1234',
    title: 'Киноклуб',
    avatar: null,
    avatarColor: '#AB3245',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '12:00',
      content: 'стикер',
    },
  },
  {
    id: 'id',
    title: 'Илья',
    avatar: null,
    avatarColor: '#7E6C63',
    unreadCount: 10,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '13:66',
      content: 'Так увлёкся работой по курсу, что совсем забыл его анонсировать на следующий год. Вот блин, как всегда всё не так, как я планировал изначально. Простите меня охохох как страшно жить и писать эти строки пойду утоплюсь хахахохо',
    },
  },
  {
    id: '1236',
    title: 'Такого времени не бывает',
    avatar: null,
    avatarColor: '#',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '14.00',
      content: 'совсем забыл',
    },
  },
  {
    id: '1237',
    title: 'Вадим',
    avatar: null,
    avatarColor: '#2917F4',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '15:12',
      content: 'круто!',
    },
  },
  {
    id: '1238',
    title: '1, 2, 3',
    avatar: null,
    avatarColor: '#3F4489',
    unreadCount: 45,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Пт',
      content: 'Миллионы россиян ежедневно выпивают по три стакана воды с примесью трёх чайных ложек самого обычного раствора из топора. Мы делаем самый насыщенный раствор из топора. Если вы купите наш раствор сейчас, то получите в подарок обыкновенную вилку.',
    },
  },
  {
    id: '1239',
    title: 'Design Destroyer',
    avatar: null,
    avatarColor: '#DB678A',
    unreadCount: 10000,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Ср',
      content: 'В 2008 году художник Jon Rafman начал собирать своё портфолио. Это портфолио настолько профессионально собрано, что все его знакомые были в восторге. Люди стояли в очереди, чтобы посмотреть на это портфолио.',
    },
  },
  {
    id: '12310',
    title: 'Day.',
    avatar: null,
    avatarColor: '#74C3BF',
    unreadCount: 99,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Пн',
      content: 'Так увлёкся работой по курсу, что совсем забыл его анонсировать. Так что анонсирую сейчас. Курс очень крутой и раскрывает не только основные темы, но и множество нюансов, которые можно обнаружить только на практике.',
    },
  },
  {
    id: '12311',
    title: 'Стас Рогозин',
    avatar: null,
    avatarColor: '#FFFFFF',
    unreadCount: 100,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: 'Пн',
      content: 'Можно или сегодня или завтра вечером.',
    },
  },
  {
    id: '12312',
    title: 'тет-а-теты',
    avatar: null,
    avatarColor: '#43F417',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '1 Мая 2022',
      content: 'И Human Interface Guidelines лучше изучить уже сегодня, иначе вы отстанете по программе.',
    },
  },
  {
    id: '12313',
    title: 'Группа № 13',
    avatar: null,
    avatarColor: '#17F4BF',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '20 Апр 2021',
      content: 'стикер',
    },
  },
  {
    id: '12314',
    title: 'Учимся на Я.Практикум!',
    avatar: null,
    avatarColor: '#BE9D26',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '15 Апр 2020',
      content: 'Как заработать много новых впечатлений от поездок в простые места? Обращайтесь в нашу экскурсионную организацию и мы покажем, как :-)',
    },
  },
  {
    id: '12315',
    title: '###',
    avatar: null,
    avatarColor: '#FF0000',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '14 Мая 2019',
      content: 'За что мне это всё?',
    },
  },
  {
    id: '12316',
    title: 'Андрей',
    avatar: null,
    avatarColor: '#FFFFFF',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '25 Апр 2018',
      content: 'Изображение',
    },
  },
  {
    id: '12317',
    title: 'Киноклуб',
    avatar: null,
    avatarColor: '#AB3245',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '2010',
      content: 'стикер',
    },
  },
  {
    id: '12318',
    title: 'Илья32',
    avatar: null,
    avatarColor: '#7E6C63',
    unreadCount: 0,
    lastMessage: {
      user: {
        first_name: 'Андрей',
        second_name: 'Pupkin',
        avatar: '/path/to/avatar.jpg',
        email: 'my@email.com',
        login: 'userLogin',
        phone: '8(911)-222-33-22',
      },
      time: '1993',
      content: 'Ребят, дайте ссылочку на материалы пожалуйста',
    },
  },
];

export const MESSAGES = [
  {
    user: {
      id: 123,
      first_name: 'Petya',
      second_name: 'Pupkin',
      display_name: 'Petya Pupkin',
      login: 'userLogin',
      email: 'my@email.com',
      phone: '89223332211',
      avatar: '/path/to/avatar.jpg',
    },
    time: '2023-04-23T14:10:19.000Z',
    content: 'Ой даже не знаю',
  },
  {
    user: {
      id: 1234,
      first_name: 'Petya',
      second_name: 'Pupkin',
      display_name: 'Petya Pupkin',
      login: 'userLogin',
      email: 'my@email.com',
      phone: '89223332211',
      avatar: '/path/to/avatar.jpg',
    },
    time: '2023-04-23T14:10:19.000Z',
    content: `
      Я тоже не смогу сегодня. Проработала я на этой бирже около 3 месяцев, и все, что я заработала это 200 рублей, да, вроде бы тоже деньги, но за такую работу, 
      я могла бы получить в 100 раз больше, дада, вы все правильно поняли, именно в 100, потому как на бирже вообще не ценят труд, а сами наверняка перепродают его за бешеные деньги.
      Работаешь, трудишься целый день, а в конце получаешь либо рублей 10, либо вообще отказ от автора и понижение рейтинга...
      Вообщем, как по мне, вы наверное уже поняли, я терпеть немогу такие сайты, где человеческий труд вообще ни во что не ставят.
    `,
  },
  {
    user: {
      id: 123,
      first_name: 'Petya',
      second_name: 'Pupkin',
      display_name: 'Petya Pupkin',
      login: 'userLogin',
      email: 'my@email.com',
      phone: '89223332211',
      avatar: '/path/to/avatar.jpg',
    },
    time: '2023-04-23T14:10:19.000Z',
    content: 'Ок',
  },
];
